management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    root: INFO

spring:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB